apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/ederqueirozdf/ocp-catalog/elasticsearch-operator/overlays/stable

patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: elasticsearch-operator
      namespace: openshift-operators-redhat
    path: patch.yaml
