{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .destinationNamespace }}
    server: {{ .destinationServer }}
  project: default
  source:
    path: {{ .path }}
    repoURL: {{ .repoURL }}
    targetRevision: HEAD
---
{{- end }}