---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
  - ../../base/

patches:
  - target:
      kind: DataProtectionApplication
      name: oadp-dpa-prd
    patch: |-
      - op: replace
        path: /spec/backupLocations/0/velero/config/s3Url
        value: "http://s3.prd.com.br"
